language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get update
  - sudo apt-get install libgdal-dev
